language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      # The latest current OSX image:
      # https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    - os: osx
      osx_image: xcode8.3

services:
  - docker

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./setup.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y; sudo apt-get dist-upgrade -y; docker pull buildpack-deps:zesty ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./run-inside-docker.sh ; fi
